sudo: false
language: ruby
rvm:
  - 2.0
  - 2.2
  - jruby-9.0.1.0

matrix:
  allow_failures:

branches:
  only:
    - master

addons:
  postgresql: "9.4"

env:
  - REDMINE_VER=2.6-stable
  - REDMINE_VER=3.1-stable
  - REDMINE_VER=master

install: "echo skip bundle install"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - export TESTSPACE=`pwd`/testspace
  - export NAME_OF_PLUGIN=redmine_hoptoad_server
  - export PATH_TO_PLUGIN=`pwd`
  - export PATH_TO_REDMINE=$TESTSPACE/redmine
  - mkdir $TESTSPACE
  - cp test/support/* $TESTSPACE/
  - bash -x ./travis.sh
